parameters:
    job_manager.class: Innonic\JobBundle\Services\JobManager

services:
    job_manager:
        class: %job_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
#services:
#    job.example:
#        class: Innonic\JobBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
