security:

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:             ROLE_USER
        ROLE_SUPER_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
              users:
                admin: { password: admin, roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_area:
            pattern: ^/admin
            anonymous: ~
            http_basic:
            form_login:
              login_path: innonic_job_security_login
              check_path: innonic_job_security_logincheck
            logout:
              path: innonic_job_security_logout
              target: /
            access_denied_url: access_denied

        main:
            pattern: ^/new
            anonymous: ~
            http_basic:
            form_login:
              login_path: innonic_job_user_login
              check_path: innonic_job_user_logincheck
            logout:
              path: innonic_job_user_logout
              target: /
            access_denied_url: access_denied

    access_control:
      - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, roles: ROLE_ADMIN }
      - { path: ^/new, roles: ROLE_USER }