<?php

namespace Innonic\JobBundle\Repository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByKeyWord($keyword)
    {
        $qb = $this->getQueryBuilder()
            ->where('like ' . '%'.$keyword.'%');

        return $qb->getQuery()->getResult();
    }

    private function getQueryBuilder(){
        $em = $this->getEntityManager();
        $qb = $em->getRepository('JobBundle:Job')
            ->createQueryBuilder('p');

        return $qb;
    }
}
